show_note_common_homepage:
    path:       /
    defaults:   { _controller: ShowNoteCommonBundle:Default:index }

show_note_common_login:
    path:       /login
    defaults:   { _controller: ShowNoteCommonBundle:Login:login }

show_note_common_update:
    path:       /update
    defaults:   { _controller: ShowNoteCommonBundle:Update:update }
